<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="../Transactions.Domain/EWallet.Modules.Transactions.Domain.csproj" />
    <ProjectReference Include="../../Wallets/Wallets.Application/EWallet.Modules.Wallets.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/EWallet.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
