<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <ProjectReference Include="../Merchants.Application/EWallet.Modules.Merchants.Application.csproj" />
    <ProjectReference Include="../../Wallets/Wallets.Infrastructure/EWallet.Modules.Wallets.Infrastructure.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/EWallet.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
