<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="../Identity.Domain/EWallet.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/EWallet.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
